from typing import Literal, TypeAlias

from pydantic import BaseModel, Field


class CnaeKeywords(BaseModel):
    """Keywords generated for a job description to match against CNAE classes."""

    keywords: list[str] = Field(
        ...,
        description="Lista de até 10 palavras-chave que descrevem a atividade econômica do trabalho.",
        max_length=10,
        examples=[
            "construcao",
            "transporte",
            "comercio",
            "saude",
            "tecnologia",
        ],
    )


class CnaeSelection(BaseModel):
    """Selected CNAE class for a job description with reasoning."""

    classe_cnae: str = Field(
        ...,
        description="A classe CNAE selecionada que melhor representa a atividade econômica.",
    )
    confidence: str = Field(
        ...,
        description="Nível de confiança na seleção: 'alto', 'médio' ou 'baixo'.",
    )
    reasoning: str = Field(
        ...,
        description="Breve explicação do motivo da escolha desta classe CNAE.",
    )


ClasseCnae: TypeAlias = Literal[
    "Abate de reses, exceto suínos",
    "Abate de suínos, aves e outros pequenos animais",
    "Acabamentos em fios, tecidos e artefatos têxteis",
    "Administração de bolsas e mercados de balcão organizados",
    "Administração de cartões de crédito",
    "Administração de consórcios para aquisição de bens e direitos",
    "Administração pública em geral",
    "Agenciamento de espaços para publicidade, exceto em veículos de comunicação",
    "Agências de fomento",
    "Agências de notícias",
    "Agências de publicidade",
    "Agências de viagens",
    "Aluguel de equipamentos recreativos e esportivos",
    "Aluguel de fitas de vídeo, DVDs e similares",
    "Aluguel de máquinas e equipamentos agrícolas sem operador",
    "Aluguel de máquinas e equipamentos não especificados anteriormente",
    "Aluguel de máquinas e equipamentos para construção sem operador",
    "Aluguel de máquinas e equipamentos para escritório",
    "Aluguel de objetos do vestuário, jóias e acessórios",
    "Aluguel de objetos pessoais e domésticos não especificados anteriormente",
    "Aparelhamento e outros trabalhos em pedras",
    "Aquicultura em água doce",
    "Aquicultura em água salgada e salobra",
    "Armazenamento",
    "Arrendamento mercantil",
    "Artes cênicas, espetáculos e atividades complementares",
    "Atividades associativas não especificadas anteriormente",
    "Atividades auxiliares dos seguros, da previdência complementar e dos planos de saúde não especificadas anteriormente",
    "Atividades auxiliares dos serviços financeiros não especificadas anteriormente",
    "Atividades auxiliares dos transportes aéreos",
    "Atividades auxiliares dos transportes aquaviários não especificadas anteriormente",
    "Atividades auxiliares dos transportes terrestres não especificadas anteriormente",
    "Atividades de administração de fundos por contrato ou comissão",
    "Atividades de agenciamento marítimo",
    "Atividades de apoio à agricultura",
    "Atividades de apoio à educação",
    "Atividades de apoio à extração de minerais, exceto petróleo e gás natural",
    "Atividades de apoio à extração de petróleo e gás natural",
    "Atividades de apoio à gestão de saúde",
    "Atividades de apoio à pecuária",
    "Atividades de apoio à produção florestal",
    "Atividades de assistência a idosos, deficientes físicos, imunodeprimidos e convalescentes prestadas em residências coletivas e particulares",
    "Atividades de assistência psicossocial e à saúde a portadores de distúrbios psíquicos, deficiência mental e dependência química",
    "Atividades de assistência social prestadas em residências coletivas e particulares",
    "Atividades de associações de defesa de direitos sociais",
    "Atividades de atenção à saúde humana não especificadas anteriormente",
    "Atividades de atenção ambulatorial executadas por médicos e odontólogos",
    "Atividades de atendimento hospitalar",
    "Atividades de bibliotecas e arquivos",
    "Atividades de cobrança e informações cadastrais",
    "Atividades de condicionamento físico",
    "Atividades de consultoria em gestão empresarial",
    "Atividades de contabilidade, consultoria e auditoria contábil e tributária",
    "Atividades de Correio",
    "Atividades de ensino não especificadas anteriormente",
    "Atividades de exibição cinematográfica",
    "Atividades de exploração de jogos de azar e apostas",
    "Atividades de fornecimento de infraestrutura de apoio e assistência a paciente no domicílio",
    "Atividades de gravação de som e de edição de música",
    "Atividades de intermediários em transações de títulos, valores mobiliários e mercadorias",
    "Atividades de investigação particular",
    "Atividades de jardins botânicos, zoológicos, parques nacionais, reservas ecológicas e áreas de proteção ambiental",
    "Atividades de limpeza não especificadas anteriormente",
    "Atividades de malote e de entrega",
    "Atividades de monitoramento de sistemas de segurança",
    "Atividades de museus e de exploração, restauração artística e conservação de lugares e prédios históricos e atrações similares",
    "Atividades de organização de eventos, exceto culturais e esportivos",
    "Atividades de organizações associativas ligadas à cultura e à arte",
    "Atividades de organizações associativas patronais e empresariais",
    "Atividades de organizações associativas profissionais",
    "Atividades de organizações políticas",
    "Atividades de organizações religiosas",
    "Atividades de organizações sindicais",
    "Atividades de pós-colheita",
    "Atividades de pós-produção cinematográfica, de vídeos e de programas de televisão",
    "Atividades de produção cinematográfica, de vídeos e de programas de televisão",
    "Atividades de profissionais da área de saúde, exceto médicos e odontólogos",
    "Atividades de publicidade não especificadas anteriormente",
    "Atividades de rádio",
    "Atividades de recreação e lazer não especificadas anteriormente",
    "Atividades de serviços de complementação diagnóstica e terapêutica",
    "Atividades de serviços pessoais não especificadas anteriormente",
    "Atividades de serviços prestados principalmente às empresas não especificadas anteriormente",
    "Atividades de teleatendimento",
    "Atividades de televisão aberta",
    "Atividades de transporte de valores",
    "Atividades de vigilância e segurança privada",
    "Atividades esportivas não especificadas anteriormente",
    "Atividades fotográficas e similares",
    "Atividades funerárias e serviços relacionados",
    "Atividades imobiliárias de imóveis próprios",
    "Atividades jurídicas, exceto cartórios",
    "Atividades paisagísticas",
    "Atividades profissionais, científicas e técnicas não especificadas anteriormente",
    "Atividades relacionadas a esgoto, exceto a gestão de redes",
    "Atividades relacionadas à organização do transporte de carga",
    "Atividades técnicas relacionadas à arquitetura e engenharia",
    "Atividades veterinárias",
    "Avaliação de riscos e perdas",
    "Banco Central",
    "Bancos comerciais",
    "Bancos de câmbio e outras instituições de intermediação não monetária",
    "Bancos de desenvolvimento",
    "Bancos de investimento",
    "Bancos múltiplos, com carteira comercial",
    "Bancos múltiplos, sem carteira comercial",
    "Beneficiamento de arroz e fabricação de produtos do arroz",
    "Cabeleireiros e outras atividades de tratamento de beleza",
    "Caça e serviços relacionados",
    "Caixas econômicas",
    "Captação, tratamento e distribuição de água",
    "Carga e descarga",
    "Cartórios",
    "Clubes sociais, esportivos e similares",
    "Coleta de resíduos não perigosos",
    "Coleta de resíduos perigosos",
    "Comércio a varejo e por atacado de veículos automotores",
    "Comércio ambulante e outros tipos de comércio varejista",
    "Comércio atacadista de animais vivos, alimentos para animais e matérias-primas agrícolas, exceto café e soja",
    "Comércio atacadista de artigos de escritório e de papelaria; livros, jornais e outras publicações",
    "Comércio atacadista de artigos do vestuário e acessórios",
    "Comércio atacadista de bebidas",
    "Comércio atacadista de café em grão",
    "Comércio atacadista de calçados e artigos de viagem",
    "Comércio atacadista de carnes, produtos da carne e pescado",
    "Comércio atacadista de cereais e leguminosas beneficiados, farinhas, amidos e féculas",
    "Comércio atacadista de cimento",
    "Comércio atacadista de combustíveis sólidos, líquidos e gasosos, exceto gás natural e GLP",
    "Comércio atacadista de componentes eletrônicos e equipamentos de telefonia e comunicação",
    "Comércio atacadista de computadores, periféricos e suprimentos de informática",
    "Comércio atacadista de cosméticos, produtos de perfumaria e de higiene pessoal",
    "Comércio atacadista de defensivos agrícolas, adubos, fertilizantes e corretivos do solo",
    "Comércio atacadista de energia elétrica",
    "Comércio atacadista de equipamentos e artigos de uso pessoal e doméstico não especificados anteriormente",
    "Comércio atacadista de ferragens e ferramentas",
    "Comércio atacadista de gás liquefeito de petróleo (GLP)",
    "Comércio atacadista de hortifrutigranjeiros",
    "Comércio atacadista de instrumentos e materiais para uso médico, cirúrgico, ortopédico e odontológico",
    "Comércio atacadista de leite e laticínios",
    "Comércio atacadista de madeira e produtos derivados",
    "Comércio atacadista de máquinas e equipamentos para uso comercial; partes e peças",
    "Comércio atacadista de máquinas e equipamentos para uso industrial; partes e peças",
    "Comércio atacadista de máquinas, aparelhos e equipamentos não especificados anteriormente; partes e peças",
    "Comércio atacadista de máquinas, aparelhos e equipamentos para uso agropecuário; partes e peças",
    "Comércio atacadista de máquinas, aparelhos e equipamentos para uso odonto-médico-hospitalar; partes e peças",
    "Comércio atacadista de máquinas, equipamentos para terraplenagem, mineração e construção; partes e peças",
    "Comércio atacadista de material elétrico",
    "Comércio atacadista de mercadorias em geral, com predominância de insumos agropecuários",
    "Comércio atacadista de mercadorias em geral, com predominância de produtos alimentícios",
    "Comércio atacadista de mercadorias em geral, sem predominância de alimentos ou de insumos agropecuários",
    "Comércio atacadista de papel e papelão em bruto e de embalagens",
    "Comércio atacadista de produtos alimentícios em geral",
    "Comércio atacadista de produtos do fumo",
    "Comércio atacadista de produtos farmacêuticos para uso humano e veterinário",
    "Comércio atacadista de produtos químicos e petroquímicos, exceto agroquímicos",
    "Comércio atacadista de produtos siderúrgicos e metalúrgicos, exceto para construção",
    "Comércio atacadista de resíduos e sucatas",
    "Comércio atacadista de soja",
    "Comércio atacadista de tecidos, artefatos de tecidos e de armarinho",
    "Comércio atacadista especializado de materiais de construção não especificados anteriormente e de materiais de construção em geral",
    "Comércio atacadista especializado de outros produtos intermediários não especificados anteriormente",
    "Comércio atacadista especializado em produtos alimentícios não especificados anteriormente",
    "Comércio de peças e acessórios para veículos automotores",
    "Comércio por atacado e a varejo de motocicletas, peças e acessórios",
    "Comércio varejista de artigos de óptica",
    "Comércio varejista de artigos de uso doméstico não especificados anteriormente",
    "Comércio varejista de artigos do vestuário e acessórios",
    "Comércio varejista de artigos médicos e ortopédicos",
    "Comércio varejista de artigos recreativos e esportivos",
    "Comércio varejista de artigos usados",
    "Comércio varejista de bebidas",
    "Comércio varejista de calçados e artigos de viagem",
    "Comércio varejista de carnes e pescados - açougues e peixarias",
    "Comércio varejista de combustíveis para veículos automotores",
    "Comércio varejista de cosméticos, produtos de perfumaria e de higiene pessoal",
    "Comércio varejista de discos, CDs, DVDs e fitas",
    "Comércio varejista de ferragens, madeira e materiais de construção",
    "Comércio varejista de gás liqüefeito de petróleo (GLP)",
    "Comércio varejista de hortifrutigranjeiros",
    "Comércio varejista de jóias e relógios",
    "Comércio varejista de livros, jornais, revistas e papelaria",
    "Comércio varejista de lubrificantes",
    "Comércio varejista de material elétrico",
    "Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios - hipermercados e supermercados",
    "Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios - minimercados, mercearias e armazéns",
    "Comércio varejista de mercadorias em geral, sem predominância de produtos alimentícios",
    "Comércio varejista de outros produtos novos não especificados anteriormente",
    "Comércio varejista de produtos alimentícios em geral ou especializado em produtos alimentícios não especificados anteriormente; produtos do fumo",
    "Comércio varejista de produtos de padaria, laticínio, doces, balas e semelhantes",
    "Comércio varejista de produtos farmacêuticos para uso humano e veterinário",
    "Comércio varejista de tintas e materiais para pintura",
    "Comércio varejista de vidros",
    "Comércio varejista especializado de eletrodomésticos e equipamentos de áudio e vídeo",
    "Comércio varejista especializado de equipamentos de telefonia e comunicação",
    "Comércio varejista especializado de equipamentos e suprimentos de informática",
    "Comércio varejista especializado de instrumentos musicais e acessórios",
    "Comércio varejista especializado de móveis, colchoaria e artigos de iluminação",
    "Comércio varejista especializado de peças e acessórios para aparelhos eletroeletrônicos para uso doméstico, exceto informática e comunicação",
    "Comércio varejista especializado de tecidos e artigos de cama, mesa e banho",
    "Concessionárias de rodovias, pontes, túneis e serviços relacionados",
    "Condomínios prediais",
    "Confecção de peças do vestuário, exceto roupas íntimas",
    "Confecção de roupas íntimas",
    "Confecção de roupas profissionais",
    "Construção de edifícios",
    "Construção de embarcações e estruturas flutuantes",
    "Construção de embarcações para esporte e lazer",
    "Construção de obras de arte especiais",
    "Construção de redes de abastecimento de água, coleta de esgoto e construções correlatas",
    "Construção de redes de transportes por dutos, exceto para água e esgoto",
    "Construção de rodovias e ferrovias",
    "Consultoria em tecnologia da informação",
    "Coquerias",
    "Corretores e agentes de seguros, de planos de previdência complementar e de saúde",
    "Crédito cooperativo",
    "Crédito imobiliário",
    "Criação artística",
    "Criação de animais não especificados anteriormente",
    "Criação de aves",
    "Criação de bovinos",
    "Criação de caprinos e ovinos",
    "Criação de outros animais de grande porte",
    "Criação de suínos",
    "Cultivo de algodão herbáceo e de outras fibras de lavoura temporária",
    "Cultivo de cacau",
    "Cultivo de café",
    "Cultivo de cana-de-açúcar",
    "Cultivo de cereais",
    "Cultivo de flores e plantas ornamentais",
    "Cultivo de frutas de lavoura permanente, exceto laranja e uva",
    "Cultivo de fumo",
    "Cultivo de laranja",
    "Cultivo de oleaginosas de lavoura temporária, exceto soja",
    "Cultivo de plantas de lavoura permanente não especificadas anteriormente",
    "Cultivo de plantas de lavoura temporária não especificadas anteriormente",
    "Cultivo de soja",
    "Cultivo de uva",
    "Curtimento e outras preparações de couro",
    "Defesa Civil",
    "Defesa",
    "Demolição e preparação de canteiros de obras",
    "Descontaminação e outros serviços de gestão de resíduos",
    "Desdobramento de madeira",
    "Desenvolvimento de programas de computador sob encomenda",
    "Desenvolvimento e licenciamento de programas de computador customizáveis",
    "Desenvolvimento e licenciamento de programas de computador não customizáveis",
    "Design e decoração de interiores",
    "Distribuição cinematográfica, de vídeo e de programas de televisão",
    "Distribuição de energia elétrica",
    "Edição de cadastros, listas e outros produtos gráficos",
    "Edição de jornais",
    "Edição de livros",
    "Edição de revistas",
    "Edição integrada à impressão de cadastros, listas e outros produtos gráficos",
    "Edição integrada à impressão de jornais",
    "Edição integrada à impressão de livros",
    "Edição integrada à impressão de revistas",
    "Educação infantil - creche",
    "Educação infantil - pré-escola",
    "Educação profissional de nível técnico",
    "Educação profissional de nível tecnológico",
    "Educação superior - graduação e pós-graduação",
    "Educação superior - graduação",
    "Educação superior - pós-graduação e extensão",
    "Ensino de arte e cultura",
    "Ensino de esportes",
    "Ensino de idiomas",
    "Ensino fundamental",
    "Ensino médio",
    "Envasamento e empacotamento sob contrato",
    "Estacionamento de veículos",
    "Extração de carvão mineral",
    "Extração de gemas (pedras preciosas e semipreciosas)",
    "Extração de minerais metálicos não ferrosos não especificados anteriormente",
    "Extração de minerais não metálicos não especificados anteriormente",
    "Extração de minerais para fabricação de adubos, fertilizantes e outros produtos químicos",
    "Extração de minerais radioativos",
    "Extração de minério de alumínio",
    "Extração de minério de estanho",
    "Extração de minério de ferro",
    "Extração de minério de manganês",
    "Extração de minério de metais preciosos",
    "Extração de pedra, areia e argila",
    "Extração de petróleo e gás natural",
    "Extração e refino de sal marinho e sal-gema",
    "Fabricação de acessórios do vestuário, exceto para segurança e proteção",
    "Fabricação de açúcar em bruto",
    "Fabricação de açúcar refinado",
    "Fabricação de adesivos e selantes",
    "Fabricação de aditivos de uso industrial",
    "Fabricação de adubos e fertilizantes",
    "Fabricação de aeronaves",
    "Fabricação de aguardentes e outras bebidas destiladas",
    "Fabricação de águas envasadas",
    "Fabricação de álcool",
    "Fabricação de alimentos e pratos prontos",
    "Fabricação de alimentos para animais",
    "Fabricação de amidos e féculas de vegetais e de óleos de milho",
    "Fabricação de aparelhos de recepção, reprodução, gravação e amplificação de áudio e vídeo",
    "Fabricação de aparelhos e equipamentos de ar condicionado",
    "Fabricação de aparelhos e equipamentos de medida, teste e controle",
    "Fabricação de aparelhos e equipamentos para distribuição e controle de energia elétrica",
    "Fabricação de aparelhos e equipamentos para instalações térmicas",
    "Fabricação de aparelhos eletrodomésticos não especificados anteriormente",
    "Fabricação de aparelhos eletromédicos e eletroterapêuticos e equipamentos de irradiação",
    "Fabricação de aparelhos telefônicos e de outros equipamentos de comunicação",
    "Fabricação de artefatos de borracha não especificados anteriormente",
    "Fabricação de artefatos de concreto, cimento, fibrocimento, gesso e materiais semelhantes",
    "Fabricação de artefatos de cordoaria",
    "Fabricação de artefatos de couro não especificados anteriormente",
    "Fabricação de artefatos de madeira, palha, cortiça, vime e material trançado não especificados anteriormente, exceto móveis",
    "Fabricação de artefatos de material plástico não especificados anteriormente",
    "Fabricação de artefatos de tanoaria e de embalagens de madeira",
    "Fabricação de artefatos de tapeçaria",
    "Fabricação de artefatos para pesca e esporte",
    "Fabricação de artefatos têxteis para uso doméstico",
    "Fabricação de artigos de cutelaria",
    "Fabricação de artigos de metal para uso doméstico e pessoal",
    "Fabricação de artigos de serralheria, exceto esquadrias",
    "Fabricação de artigos de vidro",
    "Fabricação de artigos do vestuário, produzidos em malharias e tricotagens, exceto meias",
    "Fabricação de artigos para viagem, bolsas e semelhantes de qualquer material",
    "Fabricação de automóveis, camionetas e utilitários",
    "Fabricação de baterias e acumuladores para veículos automotores",
    "Fabricação de bicicletas e triciclos não motorizados",
    "Fabricação de bijuterias e artefatos semelhantes",
    "Fabricação de biocombustíveis, exceto álcool",
    "Fabricação de biscoitos e bolachas",
    "Fabricação de brinquedos e jogos recreativos",
    "Fabricação de cabines, carrocerias e reboques para veículos automotores",
    "Fabricação de cal e gesso",
    "Fabricação de calçados de couro",
    "Fabricação de calçados de materiais não especificados anteriormente",
    "Fabricação de calçados de material sintético",
    "Fabricação de caldeiras geradoras de vapor, exceto para aquecimento central e para veículos",
    "Fabricação de caminhões e ônibus",
    "Fabricação de cartolina e papel-cartão",
    "Fabricação de catalisadores",
    "Fabricação de celulose e outras pastas para a fabricação de papel",
    "Fabricação de chapas e de embalagens de papelão ondulado",
    "Fabricação de cimento",
    "Fabricação de cloro e álcalis",
    "Fabricação de colchões",
    "Fabricação de componentes eletrônicos",
    "Fabricação de compressores",
    "Fabricação de conservas de frutas",
    "Fabricação de conservas de legumes e outros vegetais",
    "Fabricação de cosméticos, produtos de perfumaria e de higiene pessoal",
    "Fabricação de cronômetros e relógios",
    "Fabricação de defensivos agrícolas",
    "Fabricação de desinfestantes domissanitários",
    "Fabricação de elastômeros",
    "Fabricação de embalagens de cartolina e papel-cartão",
    "Fabricação de embalagens de material plástico",
    "Fabricação de embalagens de papel",
    "Fabricação de embalagens de vidro",
    "Fabricação de embalagens metálicas",
    "Fabricação de equipamento bélico pesado, armas de fogo e munições",
    "Fabricação de equipamentos de informática",
    "Fabricação de equipamentos de transmissão para fins industriais",
    "Fabricação de equipamentos de transporte não especificados anteriormente",
    "Fabricação de equipamentos e acessórios para segurança e proteção pessoal e profissional",
    "Fabricação de equipamentos e aparelhos elétricos não especificados anteriormente",
    "Fabricação de equipamentos e instrumentos ópticos, fotográficos e cinematográficos",
    "Fabricação de equipamentos hidráulicos e pneumáticos, exceto válvulas",
    "Fabricação de equipamentos para irrigação agrícola",
    "Fabricação de equipamentos transmissores de comunicação",
    "Fabricação de escovas, pincéis e vassouras",
    "Fabricação de especiarias, molhos, temperos e condimentos",
    "Fabricação de esquadrias de metal",
    "Fabricação de estruturas de madeira e de artigos de carpintaria para construção",
    "Fabricação de estruturas metálicas",
    "Fabricação de explosivos",
    "Fabricação de farinha de mandioca e derivados",
    "Fabricação de farinha de milho e derivados, exceto óleos de milho",
    "Fabricação de ferramentas",
    "Fabricação de fibras artificiais e sintéticas",
    "Fabricação de fios, cabos e condutores elétricos isolados",
    "Fabricação de fogões, refrigeradores e máquinas de lavar e secar para uso doméstico",
    "Fabricação de gases industriais",
    "Fabricação de geradores, transformadores e motores elétricos",
    "Fabricação de impermeabilizantes, solventes e produtos afins",
    "Fabricação de instrumentos e materiais para uso médico e odontológico e de artigos ópticos",
    "Fabricação de instrumentos musicais",
    "Fabricação de intermediários para fertilizantes",
    "Fabricação de intermediários para plastificantes, resinas e fibras",
    "Fabricação de laminados planos e tubulares de material plástico",
    "Fabricação de lâmpadas e outros equipamentos de iluminação",
    "Fabricação de laticínios",
    "Fabricação de linhas para costurar e bordar",
    "Fabricação de locomotivas, vagões e outros materiais rodantes",
    "Fabricação de madeira laminada e de chapas de madeira compensada, prensada e aglomerada",
    "Fabricação de malte, cervejas e chopes",
    "Fabricação de máquinas e aparelhos de refrigeração e ventilação para uso industrial e comercial",
    "Fabricação de máquinas e equipamentos de uso geral não especificados anteriormente",
    "Fabricação de máquinas e equipamentos para a agricultura e pecuária, exceto para irrigação",
    "Fabricação de máquinas e equipamentos para a indústria do plástico",
    "Fabricação de máquinas e equipamentos para a indústria têxtil",
    "Fabricação de máquinas e equipamentos para a prospecção e extração de petróleo",
    "Fabricação de máquinas e equipamentos para as indústrias de alimentos, bebidas e fumo",
    "Fabricação de máquinas e equipamentos para as indústrias de celulose, papel e papelão e artefatos",
    "Fabricação de máquinas e equipamentos para as indústrias do vestuário, do couro e de calçados",
    "Fabricação de máquinas e equipamentos para saneamento básico e ambiental",
    "Fabricação de máquinas e equipamentos para terraplenagem, pavimentação e construção, exceto tratores",
    "Fabricação de máquinas e equipamentos para uso industrial específico não especificados anteriormente",
    "Fabricação de máquinas para a indústria metalúrgica, exceto máquinas-ferramenta",
    "Fabricação de máquinas-ferramenta",
    "Fabricação de máquinas, equipamentos e aparelhos para transporte e elevação de cargas e pessoas",
    "Fabricação de margarina e outras gorduras vegetais e de óleos não comestíveis de animais",
    "Fabricação de massas alimentícias",
    "Fabricação de material elétrico e eletrônico para veículos automotores, exceto baterias",
    "Fabricação de material elétrico para instalações em circuito de consumo",
    "Fabricação de medicamentos para uso humano",
    "Fabricação de medicamentos para uso veterinário",
    "Fabricação de meias",
    "Fabricação de mídias virgens, magnéticas e ópticas",
    "Fabricação de motocicletas",
    "Fabricação de motores e turbinas, exceto para aviões e veículos rodoviários",
    "Fabricação de móveis com predominância de madeira",
    "Fabricação de móveis com predominância de metal",
    "Fabricação de móveis de outros materiais, exceto madeira e metal",
    "Fabricação de obras de caldeiraria pesada",
    "Fabricação de óleos vegetais em bruto, exceto óleo de milho",
    "Fabricação de óleos vegetais refinados, exceto óleo de milho",
    "Fabricação de outras máquinas e equipamentos para uso na extração mineral, exceto na extração de petróleo",
    "Fabricação de outros produtos têxteis não especificados anteriormente",
    "Fabricação de papel",
    "Fabricação de partes para calçados, de qualquer material",
    "Fabricação de peças e acessórios para o sistema de direção e suspensão de veículos automotores",
    "Fabricação de peças e acessórios para o sistema de freios de veículos automotores",
    "Fabricação de peças e acessórios para o sistema motor de veículos automotores",
    "Fabricação de peças e acessórios para os sistemas de marcha e transmissão de veículos automotores",
    "Fabricação de peças e acessórios para veículos automotores não especificados anteriormente",
    "Fabricação de peças e acessórios para veículos ferroviários",
    "Fabricação de periféricos para equipamentos de informática",
    "Fabricação de pilhas, baterias e acumuladores elétricos, exceto para veículos automotores",
    "Fabricação de pneumáticos e de câmaras-de-ar",
    "Fabricação de preparações farmacêuticas",
    "Fabricação de produtos à base de café",
    "Fabricação de produtos alimentícios não especificados anteriormente",
    "Fabricação de produtos cerâmicos não refratários não especificados anteriormente",
    "Fabricação de produtos cerâmicos não refratários para uso estrutural na construção",
    "Fabricação de produtos cerâmicos refratários",
    "Fabricação de produtos de carne",
    "Fabricação de produtos de limpeza e polimento",
    "Fabricação de produtos de metal não especificados anteriormente",
    "Fabricação de produtos de minerais não metálicos não especificados anteriormente",
    "Fabricação de produtos de panificação",
    "Fabricação de produtos de papel para usos doméstico e higiênico-sanitário",
    "Fabricação de produtos de papel, cartolina, papel-cartão e papelão ondulado para uso comercial e de escritório",
    "Fabricação de produtos de pastas celulósicas, papel, cartolina, papel-cartão e papelão ondulado não especificados anteriormente",
    "Fabricação de produtos de trefilados de metal",
    "Fabricação de produtos derivados do cacau, de chocolates e confeitos",
    "Fabricação de produtos derivados do petróleo, exceto produtos do refino",
    "Fabricação de produtos diversos não especificados anteriormente",
    "Fabricação de produtos do fumo",
    "Fabricação de produtos do refino de petróleo",
    "Fabricação de produtos farmoquímicos",
    "Fabricação de produtos petroquímicos básicos",
    "Fabricação de produtos químicos inorgânicos não especificados anteriormente",
    "Fabricação de produtos químicos não especificados anteriormente",
    "Fabricação de produtos químicos orgânicos não especificados anteriormente",
    "Fabricação de refrigerantes e de outras bebidas não alcoólicas",
    "Fabricação de resinas termofixas",
    "Fabricação de resinas termoplásticas",
    "Fabricação de sabões e detergentes sintéticos",
    "Fabricação de sorvetes e outros gelados comestíveis",
    "Fabricação de sucos de frutas, hortaliças e legumes",
    "Fabricação de tanques, reservatórios metálicos e caldeiras para aquecimento central",
    "Fabricação de tecidos de malha",
    "Fabricação de tecidos especiais, inclusive artefatos",
    "Fabricação de tênis de qualquer material",
    "Fabricação de tintas de impressão",
    "Fabricação de tintas, vernizes, esmaltes e lacas",
    "Fabricação de tratores agrícolas",
    "Fabricação de tratores, exceto agrícolas",
    "Fabricação de tubos e acessórios de material plástico para uso na construção",
    "Fabricação de turbinas, motores e outros componentes e peças para aeronaves",
    "Fabricação de válvulas, registros e dispositivos semelhantes",
    "Fabricação de veículos militares de combate",
    "Fabricação de vidro plano e de segurança",
    "Fabricação de vinho",
    "Fiação de fibras artificiais e sintéticas",
    "Fornecimento e gestão de recursos humanos para terceiros",
    "Fotocópias, preparação de documentos e outros serviços especializados de apoio administrativo",
    "Fundição de ferro e aço",
    "Fundição de metais não ferrosos e suas ligas",
    "Fundos de investimento",
    "Geração de energia elétrica",
    "Gestão de ativos intangíveis não financeiros",
    "Gestão de espaços para artes cênicas, espetáculos e outras atividades artísticas",
    "Gestão de instalações de esportes",
    "Gestão de portos e terminais",
    "Gestão de redes de esgoto",
    "Gestão e administração da propriedade imobiliária",
    "Holdings de instituições financeiras",
    "Holdings de instituições não financeiras",
    "Horticultura",
    "Hotéis e similares",
    "Impressão de jornais, livros, revistas e outras publicações periódicas",
    "Impressão de materiais para outros usos",
    "Impressão de material de segurança",
    "Imunização e controle de pragas urbanas",
    "Incorporação de empreendimentos imobiliários",
    "Instalação de equipamentos não especificados anteriormente",
    "Instalação de máquinas e equipamentos industriais",
    "Instalações elétricas",
    "Instalações hidráulicas, de sistemas de ventilação e refrigeração",
    "Intermediação na compra, venda e aluguel de imóveis",
    "Justiça",
    "Lapidação de gemas e fabricação de artefatos de ourivesaria e joalheria",
    "Lavanderias, tinturarias e toalheiros",
    "Limpeza em prédios e em domicílios",
    "Locação de automóveis sem condutor",
    "Locação de mão de obra temporária",
    "Locação de meios de transporte, exceto automóveis, sem condutor",
    "Manutenção e reparação de aeronaves",
    "Manutenção e reparação de embarcações",
    "Manutenção e reparação de equipamentos e produtos não especificados anteriormente",
    "Manutenção e reparação de equipamentos eletrônicos e ópticos",
    "Manutenção e reparação de máquinas e equipamentos da indústria mecânica",
    "Manutenção e reparação de máquinas e equipamentos elétricos",
    "Manutenção e reparação de motocicletas",
    "Manutenção e reparação de tanques, reservatórios metálicos e caldeiras, exceto para veículos",
    "Manutenção e reparação de veículos automotores",
    "Manutenção e reparação de veículos ferroviários",
    "Metalurgia do alumínio e suas ligas",
    "Metalurgia do cobre",
    "Metalurgia dos metais não ferrosos e suas ligas não especificados anteriormente",
    "Metalurgia dos metais preciosos",
    "Moagem de trigo e fabricação de derivados",
    "Moagem e fabricação de produtos de origem vegetal não especificados anteriormente",
    "Montagem de instalações industriais e de estruturas metálicas",
    "Navegação de apoio",
    "Obras de acabamento",
    "Obras de engenharia civil não especificadas anteriormente",
    "Obras de fundações",
    "Obras de instalações em construções não especificadas anteriormente",
    "Obras de terraplenagem",
    "Obras de urbanização - ruas, praças e calçadas",
    "Obras para geração e distribuição de energia elétrica e para telecomunicações",
    "Obras portuárias, marítimas e fluviais",
    "Operadoras de televisão por assinatura por cabo",
    "Operadoras de televisão por assinatura por micro-ondas",
    "Operadoras de televisão por assinatura por satélite",
    "Operadores turísticos",
    "Organismos internacionais e outras instituições extraterritoriais",
    "Outras atividades de prestação de serviços de informação não especificadas anteriormente",
    "Outras atividades de serviços financeiros não especificadas anteriormente",
    "Outras atividades de telecomunicações",
    "Outras sociedades de participação, exceto holdings",
    "Outros tipos de alojamento não especificados anteriormente",
    "Parques de diversão e parques temáticos",
    "Perfurações e sondagens",
    "Pesca em água doce",
    "Pesca em água salgada",
    "Pesquisa e desenvolvimento experimental em ciências físicas e naturais",
    "Pesquisa e desenvolvimento experimental em ciências sociais e humanas",
    "Pesquisas de mercado e de opinião pública",
    "Planos de saúde",
    "Portais, provedores de conteúdo e outros serviços de informação na Internet",
    "Preparação do leite",
    "Preparação e fiação de fibras de algodão",
    "Preparação e fiação de fibras têxteis naturais, exceto algodão",
    "Preservação do pescado e fabricação de produtos do pescado",
    "Previdência complementar aberta",
    "Previdência complementar fechada",
    "Processamento industrial do fumo",
    "Produção de artefatos estampados de metal; metalurgia do pó",
    "Produção de ferro-gusa",
    "Produção de ferroligas",
    "Produção de forjados de aço e de metais não ferrosos e suas ligas",
    "Produção de gás; processamento de gás natural; distribuição de combustíveis gasosos por redes urbanas",
    "Produção de laminados longos de aço",
    "Produção de laminados planos de aço",
    "Produção de mudas e outras formas de propagação vegetal, certificadas",
    "Produção de outros tubos de ferro e aço",
    "Produção de relaminados, trefilados e perfilados de aço",
    "Produção de sementes certificadas",
    "Produção de semiacabados de aço",
    "Produção de tubos de aço com costura",
    "Produção e distribuição de vapor, água quente e ar condicionado",
    "Produção florestal - florestas nativas",
    "Produção florestal - florestas plantadas",
    "Programadoras e atividades relacionadas à televisão por assinatura",
    "Recondicionamento e recuperação de motores para veículos automotores",
    "Recuperação de materiais metálicos",
    "Recuperação de materiais não especificados anteriormente",
    "Recuperação de materiais plásticos",
    "Reforma de pneumáticos usados",
    "Regulação das atividades de saúde, educação, serviços culturais e outros serviços sociais",
    "Regulação das atividades econômicas",
    "Relações exteriores",
    "Reparação e manutenção de computadores e de equipamentos periféricos",
    "Reparação e manutenção de equipamentos de comunicação",
    "Reparação e manutenção de equipamentos eletroeletrônicos de uso pessoal e doméstico",
    "Reparação e manutenção de objetos e equipamentos pessoais e domésticos não especificados anteriormente",
    "Representantes comerciais e agentes do comércio de combustíveis, minerais, produtos siderúrgicos e químicos",
    "Representantes comerciais e agentes do comércio de eletrodomésticos, móveis e artigos de uso doméstico",
    "Representantes comerciais e agentes do comércio de madeira, material de construção e ferragens",
    "Representantes comerciais e agentes do comércio de máquinas, equipamentos, embarcações e aeronaves",
    "Representantes comerciais e agentes do comércio de matérias-primas agrícolas e animais vivos",
    "Representantes comerciais e agentes do comércio de mercadorias em geral não especializado",
    "Representantes comerciais e agentes do comércio de motocicletas, peças e acessórios",
    "Representantes comerciais e agentes do comércio de produtos alimentícios, bebidas e fumo",
    "Representantes comerciais e agentes do comércio de têxteis, vestuário, calçados e artigos de viagem",
    "Representantes comerciais e agentes do comércio de veículos automotores",
    "Representantes comerciais e agentes do comércio especializado em produtos não especificados anteriormente",
    "Reprodução de materiais gravados em qualquer suporte",
    "Resseguros",
    "Restaurantes e outros estabelecimentos de serviços de alimentação e bebidas",
    "Securitização de créditos",
    "Sedes de empresas e unidades administrativas locais",
    "Segurança e ordem pública",
    "Seguridade social obrigatória",
    "Seguros de vida",
    "Seguros não vida",
    "Seguros-saúde",
    "Seleção e agenciamento de mão de obra",
    "Serviços ambulantes de alimentação",
    "Serviços combinados de escritório e apoio administrativo",
    "Serviços combinados para apoio a edifícios, exceto condomínios prediais",
    "Serviços de acabamentos gráficos",
    "Serviços de arquitetura",
    "Serviços de assistência social sem alojamento",
    "Serviços de catering, bufê e outros serviços de comida preparada",
    "Serviços de engenharia",
    "Serviços de pré-impressão",
    "Serviços de preparação do terreno não especificados anteriormente",
    "Serviços de remoção de pacientes, exceto os serviços móveis de atendimento a urgências",
    "Serviços de reservas e outros serviços de turismo não especificados anteriormente",
    "Serviços de usinagem, solda, tratamento e revestimento em metais",
    "Serviços domésticos",
    "Serviços especializados para construção não especificados anteriormente",
    "Serviços móveis de atendimento a urgências",
    "Sociedades de capitalização",
    "Sociedades de crédito ao microempreendedor",
    "Sociedades de crédito, financiamento e investimento - financeiras",
    "Sociedades de fomento mercantil - factoring",
    "Suporte técnico, manutenção e outros serviços em tecnologia da informação",
    "Tecelagem de fios de algodão",
    "Tecelagem de fios de fibras artificiais e sintéticas",
    "Tecelagem de fios de fibras têxteis naturais, exceto algodão",
    "Telecomunicações por fio",
    "Telecomunicações por satélite",
    "Telecomunicações sem fio",
    "Terminais rodoviários e ferroviários",
    "Testes e análises técnicas",
    "Torrefação e moagem de café",
    "Transmissão de energia elétrica",
    "Transporte aéreo de carga",
    "Transporte aéreo de passageiros não regular",
    "Transporte aéreo de passageiros regular",
    "Transporte dutoviário",
    "Transporte escolar",
    "Transporte espacial",
    "Transporte ferroviário de carga",
    "Transporte marítimo de cabotagem",
    "Transporte marítimo de longo curso",
    "Transporte metroferroviário de passageiros",
    "Transporte por navegação de travessia",
    "Transporte por navegação interior de carga",
    "Transporte por navegação interior de passageiros em linhas regulares",
    "Transporte rodoviário coletivo de passageiros, com itinerário fixo, intermunicipal, interestadual e internacional",
    "Transporte rodoviário coletivo de passageiros, com itinerário fixo, municipal e em região metropolitana",
    "Transporte rodoviário coletivo de passageiros, sob regime de fretamento, e outros transportes rodoviários não especificados anteriormente",
    "Transporte rodoviário de carga",
    "Transporte rodoviário de táxi",
    "Transportes aquaviários não especificados anteriormente",
    "Tratamento de dados, provedores de serviços de aplicação e serviços de hospedagem na Internet",
    "Tratamento e disposição de resíduos não perigosos",
    "Tratamento e disposição de resíduos perigosos",
    "Trens turísticos, teleféricos e similares",
]
